-- Generated by scripts/generate-bts-projects.mjs.
-- Links the existing projects to their experience / training, without touching anything else.
-- Run in Supabase > SQL Editor after portfolio-schema.sql. Safe to re-run.

update public.projects
set experience_id = (select id from public.experiences where type = 'experience' and company ilike '%greta%' order by order_index limit 1)
where context like 'Stage · GRETA Alsace Sud%' and experience_id is null;

update public.projects
set experience_id = (select id from public.experiences where type = 'experience' and company ilike '%weishaupt%' order by order_index limit 1)
where context like 'Stage · Weishaupt%' and experience_id is null;

update public.projects
set experience_id = (select id from public.experiences where type = 'education' and (title ilike '%SIO%' or title ilike '%services informatiques%') order by order_index limit 1)
where context like 'BTS SIO%' and experience_id is null;

-- Check: every project and the experience it is linked to (empty = not linked).
select p.title as projet, e.title as experience_ou_formation
from public.projects p
left join public.experiences e on e.id = p.experience_id
order by p.order_index;
