-- Generated by scripts/generate-bts-projects.mjs. Do not edit by hand: change the script and run "npm run projects".
-- Run in Supabase > SQL Editor, AFTER portfolio-schema.sql (it needs the context / period / competencies columns).
-- Replaces every project except "portfolio-react-supabase", which is kept and only gets its metadata updated.

begin;

delete from public.projects where slug <> 'portfolio-react-supabase';

insert into public.projects
  (title, slug, description, long_description, cover_image_url, gallery, tech_stack, category, featured, published, context, period, competencies, order_index)
values
(
  'Infrastructure multisite haute disponibilité (SoCoDevl)',
  'ap1-infrastructure-haute-disponibilite-socodevl',
  'Refonte complète du SI d''une entreprise : pare-feu pfSense redondants (CARP), Active Directory, stockage TrueNAS RAID-Z1, GPO, GLPI, déploiement Clonezilla, supervision Zabbix et site distant relié en VPN.',
  'Atelier de professionnalisation n°1 du BTS SIO, mené en équipe avec Manuel Montoya sur 12 semaines (tableau Kanban Trello et diagramme de Gantt). L''entreprise SoCoDevl disposait d''un système d''information obsolète et fragmenté : il fallait garantir la haute disponibilité des accès, centraliser les données, industrialiser le parc et tout superviser.

Haute disponibilité réseau
Deux pare-feu pfSense partagent une adresse IP virtuelle CARP (192.168.1.254). pfsync réplique la table d''états et XMLRPC les règles de filtrage : si le pare-feu principal tombe, le secours reprend le trafic en moins d''une seconde, sans coupure pour les utilisateurs.

Identités et stockage
Contrôleur de domaine Windows Server 2022 (AD DS, DNS, DHCP) pour le domaine socodevi.fr. NAS TrueNAS SCALE en RAID-Z1, joint à l''Active Directory, avec des partages SMB et des ACL qui séparent un dossier commun des dossiers personnels.

Industrialisation du parc
Unités d''organisation et GPO : installation silencieuse de Firefox depuis un partage masqué, fond d''écran imposé, restrictions du panneau de configuration et lecteurs réseau montés selon l''utilisateur. Image master Windows 10 capturée puis redéployée avec Clonezilla : un poste est livré en moins de 15 minutes au lieu de plusieurs heures.

Parc et helpdesk
GLPI 10 sur Debian (LAMP) relié à l''Active Directory. L''agent GLPI est empaqueté en MSI et déployé par GPO : l''inventaire matériel et logiciel de tout le parc remonte automatiquement.

Cloud hybride, supervision et ToIP
Pont de niveau 2 OpenVPN (mode TAP) vers un site distant VMware ESXi / vCenter, supervision Zabbix (processeur, mémoire, disque, état CARP) et téléphonie sur IP avec Asterisk.',
  '/projects/ap1-infrastructure-haute-disponibilite-socodevl.png',
  '[{"url":"/projects/ap1-schema.png","caption":"Topologie de l’infrastructure SoCoDevl : pare-feu redondants, services du LAN et site distant."}]'::jsonb,
  array['pfSense', 'Windows Server 2022', 'Active Directory', 'TrueNAS', 'GLPI', 'Clonezilla', 'OpenVPN', 'VMware ESXi', 'Zabbix', 'Asterisk', 'Debian']::text[],
  'Infrastructure & virtualisation',
  true,
  true,
  'BTS SIO · Atelier de professionnalisation n°1 · en équipe',
  'Sept. – déc. 2025',
  array['Gérer le patrimoine informatique', 'Répondre aux incidents et aux demandes d''assistance et d''évolution', 'Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  1
),
(
  'Infrastructure BYOD sécurisée (SIO-Formations)',
  'ap2-infrastructure-byod-securisee',
  'Accès réseau pour appareils personnels : zones pfSense étanches, portail captif authentifié par RADIUS (NPS) sur l’Active Directory, Nextcloud et messagerie en DMZ, supervision Zabbix 7.4.',
  'Atelier de professionnalisation n°2 du BTS SIO, réalisé seul. L''organisme accueille des stagiaires et des formateurs avec leurs propres appareils (BYOD), qui ne peuvent pas rejoindre le domaine. Il fallait isoler l''environnement d''administration, authentifier nominativement chaque utilisateur avant tout accès à Internet (obligation légale de traçabilité) et fournir des outils collaboratifs.

Segmentation et filtrage
pfSense découpe le réseau en zones étanches : LAN d''administration (192.168.2.0/24), DMZ pour les services exposés, Wi-Fi BYOD (10.0.0.0/24) et WAN. Le Wi-Fi n''a accès qu''au web (HTTP/HTTPS) ; la DMZ n''ouvre vers le LAN que les flux nécessaires, comme LDAP (TCP 389).

Authentification des utilisateurs
Active Directory avec unités d''organisation et groupes (élèves, formateurs). Rôle NPS en serveur RADIUS, avec des stratégies d''accès selon le groupe. Portail captif pfSense adossé à RADIUS : toute connexion Wi-Fi est redirigée vers une authentification nominative, avec délais d''inactivité et de session.

Services collaboratifs
Nextcloud sur Debian (LAMP, MariaDB) synchronisé avec l''Active Directory via LDAP, droits liés aux groupes. Messagerie hMailServer sur le LAN et webmail Roundcube en DMZ.

Supervision
Zabbix 7.4 sur Debian 13 : agents sur les serveurs Windows et Linux (processeur, mémoire, services, espace disque, Apache), SNMP sur pfSense (bande passante, table d''états, interfaces) et tableau de bord qui isole les alertes de sévérité moyenne ou plus.',
  '/projects/ap2-infrastructure-byod-securisee.png',
  '[{"url":"/projects/ap2-schema.png","caption":"Topologie de l’infrastructure SIO-Formations : trois zones isolées par pfSense."}]'::jsonb,
  array['pfSense', 'Windows Server 2022', 'Active Directory', 'NPS / RADIUS', 'Nextcloud', 'MariaDB', 'hMailServer', 'Roundcube', 'Zabbix', 'Debian']::text[],
  'Réseau & sécurité',
  true,
  true,
  'BTS SIO · Atelier de professionnalisation n°2 · seul',
  'Janv. – mai 2026',
  array['Gérer le patrimoine informatique', 'Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  2
),
(
  'Infrastructure de virtualisation vSphere HA',
  'infrastructure-vsphere-ha',
  'Modernisation de serveurs : mise à jour des firmwares via iDRAC et iLO, grappe RAID 5 de 30 disques SAS, installation d''ESXi et de vCenter (VCSA), tests de basculement.',
  'Stage de deuxième année au GRETA Alsace Sud (Colmar).

Remise à niveau du matériel
Mise à jour des firmwares des serveurs depuis les consoles iDRAC et iLO, puis création d''une grappe RAID 5 de 30 disques SAS.

Virtualisation
Installation des hyperviseurs VMware ESXi et déploiement de vCenter (VCSA) pour administrer un cluster vSphere en haute disponibilité, avec schéma réseau à l''appui.

Validation
Tests de basculement pour vérifier la reprise des machines virtuelles en cas de perte d''un hôte.',
  '/projects/infrastructure-vsphere-ha.png',
  '[]'::jsonb,
  array['VMware ESXi', 'vCenter', 'RAID 5', 'iDRAC', 'iLO']::text[],
  'Infrastructure & virtualisation',
  true,
  true,
  'Stage · GRETA Alsace Sud',
  'Mars 2026',
  array['Gérer le patrimoine informatique', 'Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  3
),
(
  'Déploiement et migration de plus de 200 postes',
  'deploiement-parc-weishaupt',
  'Masterisation et installation de plus de 200 PC (Windows, Office 365, VPN GlobalProtect, MFA), inventaire du parc, support utilisateurs et brassage réseau.',
  'Stage de première année chez Weishaupt (Colmar).

Déploiement
Masterisation et configuration de plus de 200 postes de travail, transfert des données utilisateurs, installation d''Office 365 et de PDF24, configuration du VPN Palo Alto GlobalProtect avec authentification multifacteur.

Gestion du parc
Tableau Excel de suivi du déploiement, étiquetage du matériel et inventaire des bornes Wi-Fi Cisco (numéros de série et adresses MAC).

Support
Assistance de proximité et à distance avec TeamViewer, résolution d''incidents sur les écrans et les logiciels.

Réseau
Brassage des câbles en baie pour les postes de travail, les imprimantes et les bornes Wi-Fi.

Autonomie
Pendant une semaine, gestion seul du flux de déploiement (2 postes par jour), en coordination avec le support central en Allemagne.',
  '/projects/deploiement-parc-weishaupt.png',
  '[]'::jsonb,
  array['Windows', 'Office 365', 'GlobalProtect', 'MFA', 'TeamViewer', 'Cisco', 'Excel']::text[],
  'Déploiement & support',
  true,
  true,
  'Stage · Weishaupt',
  'Mai – juin 2025',
  array['Gérer le patrimoine informatique', 'Répondre aux incidents et aux demandes d''assistance et d''évolution', 'Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique', 'Organiser son développement professionnel']::text[],
  4
),
(
  'Sécurisation des accès distants avec RustDesk',
  'acces-distants-rustdesk',
  'Prise en main à distance auto-hébergée : serveur RustDesk sous Alpine Linux déployé avec Docker Compose, autorité de certification interne et chiffrement SSL/TLS.',
  'Stage de deuxième année au GRETA Alsace Sud.

Solution souveraine
Mise en place d''une solution de contrôle à distance auto-hébergée, pour ne plus dépendre d''un service tiers : serveur RustDesk sous Alpine Linux, déployé avec Docker Compose.

Sécurisation
Création d''une autorité de certification racine (Root CA), émission de certificats SSL/TLS et clés Ed25519.

Livrable
Guide utilisateur pour l''installation et la connexion des postes clients.',
  '/projects/acces-distants-rustdesk.png',
  '[]'::jsonb,
  array['RustDesk', 'Alpine Linux', 'Docker', 'Root CA', 'SSL/TLS']::text[],
  'Réseau & sécurité',
  false,
  true,
  'Stage · GRETA Alsace Sud',
  'Mars – avr. 2026',
  array['Répondre aux incidents et aux demandes d''assistance et d''évolution', 'Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  5
),
(
  'Maintenance et audit d''une infrastructure Proxmox',
  'maintenance-proxmox',
  'Remise en état d''un hôte Proxmox VE : passage au noyau 6.8, correction des dépôts, tunnel SSH chiffré pour contourner un blocage réseau et configuration d''un VPN Proton.',
  'Stage de deuxième année au GRETA Alsace Sud.

Maintenance
Audit d''un hôte Proxmox VE, mise à jour vers le noyau 6.8 et correction des dépôts de paquets.

Réseau
Mise en place d''un tunnel SSH chiffré pour contourner un blocage réseau, et configuration d''un VPN Proton.',
  '/projects/maintenance-proxmox.png',
  '[]'::jsonb,
  array['Proxmox VE', 'Debian', 'SSH', 'Proton VPN']::text[],
  'Infrastructure & virtualisation',
  false,
  true,
  'Stage · GRETA Alsace Sud',
  'Mars 2026',
  array['Gérer le patrimoine informatique', 'Répondre aux incidents et aux demandes d''assistance et d''évolution']::text[],
  6
),
(
  'Segmentation et brassage réseau physique',
  'segmentation-reseau-physique',
  'Installation de commutateurs et de routeurs, configuration en console (PuTTY) du NAT/PAT et mise en place d’un plan de VLAN.',
  'Stage de deuxième année au GRETA Alsace Sud.

Installation
Mise en place physique des commutateurs et des routeurs, et brassage.

Configuration
Configuration en ligne de commande via PuTTY : traduction d''adresses (NAT/PAT) et découpage du réseau selon un plan de VLAN.',
  '/projects/segmentation-reseau-physique.png',
  '[]'::jsonb,
  array['VLAN', 'NAT/PAT', 'PuTTY', 'Brassage']::text[],
  'Réseau & sécurité',
  false,
  true,
  'Stage · GRETA Alsace Sud',
  'Mars 2026',
  array['Gérer le patrimoine informatique', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  7
),
(
  'Simulation d''attaque par rançongiciel et sauvegarde',
  'simulation-rancongiciel-sauvegarde',
  'Mise en situation d''une attaque par rançongiciel pour éprouver la sauvegarde : UrBackup, stockage TrueNAS et plan de reprise d''activité.',
  'Projet en formation au BTS SIO.

Mise en situation
Simulation d''une attaque par rançongiciel pour éprouver la stratégie de sauvegarde.

Sauvegarde et reprise
Sauvegardes avec UrBackup, stockage sur TrueNAS et rédaction d''un plan de reprise d''activité (PRA).',
  '/projects/simulation-rancongiciel-sauvegarde.png',
  '[]'::jsonb,
  array['TrueNAS', 'UrBackup', 'PRA']::text[],
  'Réseau & sécurité',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Janv. – févr. 2026',
  array['Gérer le patrimoine informatique']::text[],
  8
),
(
  'Supervision et audit de sécurité (Zabbix, Nmap)',
  'supervision-audit-zabbix-nmap',
  'Tableaux de bord de supervision Zabbix, scans de vulnérabilités avec Nmap et tests d’intrusion.',
  'Projet en formation au BTS SIO.

Supervision
Création de tableaux de bord Zabbix pour suivre l''état des équipements.

Audit
Scans de vulnérabilités avec Nmap et tests d''intrusion pour vérifier l''exposition des services.',
  '/projects/supervision-audit-zabbix-nmap.png',
  '[]'::jsonb,
  array['Zabbix', 'Nmap']::text[],
  'Supervision & parc',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Oct. – nov. 2025',
  array['Gérer le patrimoine informatique', 'Répondre aux incidents et aux demandes d''assistance et d''évolution']::text[],
  9
),
(
  'Téléphonie sur IP et qualité de service',
  'telephonie-ip-asterisk',
  'Mise en place d’un serveur de téléphonie sur IP (Asterisk, 3CX) et priorisation des flux voix (QoS).',
  'Projet en formation au BTS SIO.

Téléphonie
Installation et configuration d''un serveur de téléphonie sur IP avec Asterisk et 3CX.

Qualité de service
Priorisation des flux voix sur le réseau.',
  '/projects/telephonie-ip-asterisk.png',
  '[]'::jsonb,
  array['Asterisk', '3CX', 'QoS']::text[],
  'Services & automatisation',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Nov. 2025',
  array['Mettre à disposition des utilisateurs un service informatique']::text[],
  10
),
(
  'Déploiement d''une application web en pré-production',
  'deploiement-application-web',
  'Cahier des charges technique puis installation d’un environnement Apache et SQL pour la pré-production d’une application web.',
  'Projet en formation au BTS SIO, mené en mode projet.

Cadrage
Rédaction du cahier des charges technique de l''environnement cible.

Mise en œuvre
Installation du serveur web Apache et de la base de données SQL pour la pré-production de l''application.',
  '/projects/deploiement-application-web.png',
  '[]'::jsonb,
  array['Apache', 'SQL']::text[],
  'Services & automatisation',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Nov. 2025 – janv. 2026',
  array['Travailler en mode projet', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  11
),
(
  'Gestion du patrimoine avec GLPI et OCS',
  'gestion-parc-glpi-ocs',
  'Inventaire matériel avec GLPI 10 et OCS Inventory, liaison à l’annuaire LDAP et gestion des tickets d’incident.',
  'Projet en formation au BTS SIO.

Inventaire
Inventaire matériel avec GLPI 10 et OCS Inventory.

Annuaire
Liaison LDAP pour importer les utilisateurs.

Helpdesk
Gestion des tickets d''incident.',
  '/projects/gestion-parc-glpi-ocs.png',
  '[]'::jsonb,
  array['GLPI', 'OCS Inventory', 'LDAP']::text[],
  'Supervision & parc',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Avr. – mai 2025',
  array['Gérer le patrimoine informatique', 'Répondre aux incidents et aux demandes d''assistance et d''évolution']::text[],
  12
),
(
  'Sécurité périmétrique et pare-feu (pfSense, IPFire)',
  'securite-perimetrique-pfsense',
  'Configuration de pare-feu pfSense et IPFire : filtrage des flux, zone démilitarisée (DMZ) et portail captif.',
  'Projet en formation au BTS SIO.

Mise en place de pare-feu pfSense et IPFire : règles de filtrage des flux, création d''une DMZ pour les services exposés et portail captif.',
  '/projects/securite-perimetrique-pfsense.png',
  '[]'::jsonb,
  array['pfSense', 'IPFire', 'DMZ', 'Portail captif']::text[],
  'Réseau & sécurité',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Janv. – mars 2025',
  array['Mettre à disposition des utilisateurs un service informatique']::text[],
  13
),
(
  'Automatisation des tâches d''administration',
  'automatisation-powershell',
  'Scripts PowerShell et fichiers Batch avec menus pour automatiser les tâches d’administration.',
  'Projet en formation au BTS SIO.

Écriture de scripts PowerShell complexes et de fichiers Batch proposant des menus, pour automatiser les tâches d''administration récurrentes.',
  '/projects/automatisation-powershell.png',
  '[]'::jsonb,
  array['PowerShell', 'Batch', 'Windows Server']::text[],
  'Services & automatisation',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Janv. – févr. 2025',
  array['Gérer le patrimoine informatique', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  14
),
(
  'Services de domaine Active Directory',
  'services-domaine-active-directory',
  'Contrôleur de domaine Windows Server, stratégies de groupe pour les lecteurs réseau et scripts de connexion.',
  'Projet en formation au BTS SIO.

Installation d''un contrôleur de domaine Active Directory, stratégies de groupe (GPO) pour les lecteurs réseau et scripts de connexion.',
  '/projects/services-domaine-active-directory.png',
  '[]'::jsonb,
  array['Windows Server', 'Active Directory', 'GPO']::text[],
  'Services & automatisation',
  false,
  true,
  'BTS SIO · Lycée Camille Sée',
  'Nov. – déc. 2024',
  array['Gérer le patrimoine informatique', 'Mettre à disposition des utilisateurs un service informatique']::text[],
  15
),
(
  'Veille : Debian ou Alpine Linux pour un serveur ?',
  'veille-debian-alpine',
  'Étude comparative de Debian et d’Alpine Linux comme systèmes serveur, appuyée par des installations en bare metal.',
  'Veille technologique pendant le stage au GRETA Alsace Sud.

Comparaison de Debian et d''Alpine Linux pour un usage serveur, avec des installations en bare metal pour appuyer l''étude sur des tests réels.',
  '/projects/veille-debian-alpine.png',
  '[]'::jsonb,
  array['Debian', 'Alpine Linux']::text[],
  'Veille & web',
  false,
  true,
  'Stage · GRETA Alsace Sud',
  'Mars – avr. 2026',
  array['Organiser son développement professionnel']::text[],
  16
);

update public.projects set
  category = 'Veille & web',
  context = 'BTS SIO · Lycée Camille Sée',
  period = 'Mai 2025 – janv. 2026',
  tech_stack = array['React', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Vite']::text[],
  competencies = array['Organiser son développement professionnel']::text[],
  cover_image_url = '/projects/portfolio-react-supabase.png',
  featured = false,
  order_index = 17
where slug = 'portfolio-react-supabase';

-- Link each project to its experience / training (Parcours page pop-ups).
update public.projects
set experience_id = (select id from public.experiences where type = 'experience' and company ilike '%greta%' order by order_index limit 1)
where context like 'Stage · GRETA Alsace Sud%' and experience_id is null;

update public.projects
set experience_id = (select id from public.experiences where type = 'experience' and company ilike '%weishaupt%' order by order_index limit 1)
where context like 'Stage · Weishaupt%' and experience_id is null;

update public.projects
set experience_id = (select id from public.experiences where type = 'education' and (title ilike '%SIO%' or title ilike '%services informatiques%') order by order_index limit 1)
where context like 'BTS SIO%' and experience_id is null;

commit;
